#!/bin/sh

if [ -x /usr/sbin/setcap ]; then /usr/sbin/setcap cap_sys_nice+eip /usr/local/frc/JDK/bin/java ; fi

echo /usr/local/frc/JDK/lib >> /etc/ld.so.conf.d/java_libs.conf

if [ -x /sbin/ldconfig ]; then /sbin/ldconfig ; fi
