name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: ./build-docker.sh
      - uses: actions/upload-artifact@v4
        with:
          name: JDK
          path: |
            *.ipk
            jdk_*.tar.gz
